project_id = "dnyjlmtiliqkpxwsgqyn"

[storage]
file_size_limit = "250MB"

[functions.process-email-queue]
verify_jwt = true

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.send-gmail-email]
verify_jwt = false

[functions.send-landing-page-confirmation]
verify_jwt = false

[functions.resend-landing-page-confirmation]
verify_jwt = true


[functions.verify-nevorai-member]
verify_jwt = false

[functions.confirm-nevorai-otp]
verify_jwt = false

[functions.check-funnel-view-limit]
verify_jwt = false

[functions.get-funnel-data]
verify_jwt = false


[functions.razorpay-webhook]
verify_jwt = false

[functions.razorpay-portal]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send-text]
verify_jwt = false

[functions.whatsapp-scheduler]
verify_jwt = false

[functions.whatsapp-send-otp]
verify_jwt = false

[functions.whatsapp-verify-otp]
verify_jwt = false

[functions.lookup-email-by-phone]
verify_jwt = false


